"""Idea store mixin for managing policy ideas.

Provides CRUD and filtering/sorting for ideas submitted by humans
or generated by AI.  Each idea tracks its evaluation lifecycle:
pending -> evaluating -> evaluated (or archived at any point).
"""

from __future__ import annotations

import logging
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


@dataclass
class Idea:
    """An idea record from the database."""

    id: str
    text: str
    source: str  # "human" or "AI"
    target_objective: str | None  # "layer-slug/filename.md" or None
    status: str  # pending, evaluating, evaluated, archived
    submitted_by: str  # user email or "system"
    submitted_at: datetime
    evaluation_started_at: datetime | None
    evaluation_completed_at: datetime | None


class IdeaStoreMixin:
    """Mixin providing idea CRUD and listing with filtering/sorting.

    Requires ``self.conn`` (a ``sqlite3.Connection``) to be set by the
    base store class.
    """

    conn: sqlite3.Connection  # Provided by BaseStore

    # ------------------------------------------------------------------
    # Create
    # ------------------------------------------------------------------

    def create_idea(
        self,
        text: str,
        source: str,
        target_objective: str | None = None,
        submitted_by: str = "system",
    ) -> str:
        """Create an idea record with status 'pending'.

        Args:
            text: The idea text content.
            source: Either ``"human"`` or ``"AI"``.
            target_objective: Optional scoping reference
                (``"layer-slug/filename.md"``).
            submitted_by: User email for human submissions,
                ``"system"`` for AI-generated.

        Returns:
            The generated idea ID.
        """
        idea_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        self.conn.execute(
            "INSERT INTO ideas "
            "(id, text, source, target_objective, status, "
            " submitted_by, submitted_at, evaluation_started_at, "
            " evaluation_completed_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                idea_id,
                text,
                source,
                target_objective,
                "pending",
                submitted_by,
                now,
                None,
                None,
            ),
        )
        self.conn.commit()
        return idea_id

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def get_idea(self, idea_id: str) -> Idea | None:
        """Return the full idea record by ID, or ``None``.

        Args:
            idea_id: The idea ID.

        Returns:
            An Idea dataclass, or None if not found.
        """
        row = self.conn.execute(
            "SELECT * FROM ideas WHERE id = ?",
            (idea_id,),
        ).fetchone()
        if not row:
            return None
        return self._row_to_idea(row)

    def list_ideas(
        self,
        status: str | None = None,
        sort_by: str = "submitted_at",
        sort_order: str = "desc",
        limit: int = 50,
        offset: int = 0,
    ) -> list[Idea]:
        """Return ideas with optional filtering and sorting.

        Args:
            status: Filter by status. If ``None`` (the default), archived
                ideas are excluded. Pass ``"archived"`` explicitly to see
                only archived ideas.
            sort_by: Column to sort by. One of ``"submitted_at"``
                (default), ``"score"``, or ``"status"``.
            sort_order: ``"asc"`` or ``"desc"`` (default).
            limit: Maximum number of results (max 200).
            offset: Number of results to skip.

        Returns:
            List of Idea records matching the filters.
        """
        # Clamp limits
        limit = max(1, min(limit, 200))
        offset = max(0, offset)

        conditions: list[str] = []
        params: list[object] = []

        if status is not None:
            conditions.append("i.status = ?")
            params.append(status)
        else:
            # Exclude archived by default
            conditions.append("i.status != 'archived'")

        where = ""
        if conditions:
            where = "WHERE " + " AND ".join(conditions)

        # Determine sort clause
        order_dir = "ASC" if sort_order.lower() == "asc" else "DESC"

        if sort_by == "score":
            # Join with idea_scores to sort by overall_score
            query = (
                f"SELECT i.* FROM ideas i "
                f"LEFT JOIN idea_scores s ON i.id = s.idea_id "
                f"{where} "
                f"ORDER BY s.overall_score {order_dir} NULLS LAST, "
                f"i.submitted_at DESC "
                f"LIMIT ? OFFSET ?"
            )
        elif sort_by == "status":
            query = (
                f"SELECT i.* FROM ideas i "
                f"{where} "
                f"ORDER BY i.status {order_dir}, i.submitted_at DESC "
                f"LIMIT ? OFFSET ?"
            )
        else:
            # Default: sort by submitted_at
            query = (
                f"SELECT i.* FROM ideas i "
                f"{where} "
                f"ORDER BY i.submitted_at {order_dir} "
                f"LIMIT ? OFFSET ?"
            )

        params.extend([limit, offset])
        rows = self.conn.execute(query, params).fetchall()
        return [self._row_to_idea(r) for r in rows]

    # ------------------------------------------------------------------
    # Update
    # ------------------------------------------------------------------

    def update_idea_status(self, idea_id: str, new_status: str) -> bool:
        """Transition the idea's status.

        Sets ``evaluation_started_at`` when moving to ``"evaluating"``
        and ``evaluation_completed_at`` when moving to ``"evaluated"``.

        Args:
            idea_id: The idea ID.
            new_status: The new status string.

        Returns:
            ``True`` if the update was applied, ``False`` if the idea
            was not found.
        """
        idea = self.get_idea(idea_id)
        if idea is None:
            return False

        # Log unusual transitions
        normal_transitions = {
            "pending": {"evaluating", "archived"},
            "evaluating": {"evaluated", "pending", "archived"},
            "evaluated": {"pending", "archived"},
            "archived": {"pending"},
        }
        allowed = normal_transitions.get(idea.status, set())
        if new_status not in allowed:
            logger.warning(
                "Unusual idea status transition: %s -> %s (idea %s)",
                idea.status,
                new_status,
                idea_id,
            )

        now = datetime.now(timezone.utc).isoformat()

        # Set timestamps based on target status
        if new_status == "evaluating":
            self.conn.execute(
                "UPDATE ideas SET status = ?, evaluation_started_at = ? WHERE id = ?",
                (new_status, now, idea_id),
            )
        elif new_status == "evaluated":
            self.conn.execute(
                "UPDATE ideas SET status = ?, evaluation_completed_at = ? WHERE id = ?",
                (new_status, now, idea_id),
            )
        else:
            self.conn.execute(
                "UPDATE ideas SET status = ? WHERE id = ?",
                (new_status, idea_id),
            )

        self.conn.commit()
        return True

    def archive_idea(self, idea_id: str) -> bool:
        """Set the idea status to 'archived'.

        Args:
            idea_id: The idea ID.

        Returns:
            ``True`` if successful, ``False`` if idea not found.
        """
        return self.update_idea_status(idea_id, "archived")

    # ------------------------------------------------------------------
    # Count
    # ------------------------------------------------------------------

    def count_ideas(self, status: str | None = None) -> int:
        """Return the count of ideas matching an optional status filter.

        Args:
            status: Optional status to filter by.

        Returns:
            The count of matching ideas.
        """
        if status is not None:
            row = self.conn.execute(
                "SELECT COUNT(*) as cnt FROM ideas WHERE status = ?",
                (status,),
            ).fetchone()
        else:
            row = self.conn.execute(
                "SELECT COUNT(*) as cnt FROM ideas",
            ).fetchone()

        return row["cnt"] if row else 0

    # ------------------------------------------------------------------
    # Row conversion
    # ------------------------------------------------------------------

    def _row_to_idea(self, row: sqlite3.Row) -> Idea:
        """Convert a database row to an Idea dataclass."""
        return Idea(
            id=row["id"],
            text=row["text"],
            source=row["source"],
            target_objective=row["target_objective"],
            status=row["status"],
            submitted_by=row["submitted_by"],
            submitted_at=datetime.fromisoformat(row["submitted_at"]),
            evaluation_started_at=(
                datetime.fromisoformat(row["evaluation_started_at"])
                if row["evaluation_started_at"]
                else None
            ),
            evaluation_completed_at=(
                datetime.fromisoformat(row["evaluation_completed_at"])
                if row["evaluation_completed_at"]
                else None
            ),
        )
